import { WorkType } from './models/jobs.enum';
import { Job } from './models/jobs.model';

export const jobsMock: Job[] = [
  {
    id: 1,
    companyName: 'Google',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    position: 'Software Engineer',
    expires: '2025-09-15',
    startingSalary: 75000,
    workType: WorkType.HYBRID,
    location: 'Mountain View, CA',
    country: 'USA',
    qualifications: 'Bachelor’s degree in Computer Science or related field',
    description:
      'Work on scalable web applications and contribute to Google Search innovations.',
    isApplied: false,
    companyAddress: '1600 Amphitheatre Parkway, Mountain View, CA 94043',
    companyIndustry: 'Technology',
    companyWebsite: 'https://about.google',
  },
  {
    id: 2,
    companyName: 'Microsoft',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    position: 'Cloud Solutions Developer',
    expires: '2025-09-20',
    startingSalary: 72000,
    workType: WorkType.REMOTE,
    location: 'Redmond, WA',
    country: 'USA',
    qualifications: 'Experience with C#, .NET, and Azure cloud services',
    description:
      'Develop enterprise-grade software solutions on the Azure platform.',
    isApplied: false,
    companyAddress: 'One Microsoft Way, Redmond, WA 98052',
    companyIndustry: 'Technology',
    companyWebsite: 'https://www.microsoft.com',
  },
  {
    id: 3,
    companyName: 'Spotify',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg',
    position: 'Frontend Developer',
    expires: '2025-09-10',
    startingSalary: 68000,
    workType: WorkType.REMOTE,
    location: 'Stockholm',
    country: 'Sweden',
    qualifications: 'Experience with React, Node.js, and GraphQL',
    description:
      'Build scalable music streaming services used by millions worldwide.',
    isApplied: false,
    companyAddress: 'Regeringsgatan 19, Stockholm, Sweden',
    companyIndustry: 'Music / Streaming',
    companyWebsite: 'https://www.spotify.com',
  },
  {
    id: 4,
    companyName: 'Amazon',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    position: 'Cloud Engineer',
    expires: '2025-10-01',
    startingSalary: 70000,
    workType: WorkType.ON_SITE,
    location: 'Seattle, WA',
    country: 'USA',
    qualifications: 'Bachelor’s degree in Computer Science or related field',
    description: 'Contribute to AWS platform and build cloud-native solutions.',
    isApplied: false,
    companyAddress: '410 Terry Ave N, Seattle, WA 98109',
    companyIndustry: 'E-commerce & Cloud Computing',
    companyWebsite: 'https://www.amazon.com',
  },
  {
    id: 5,
    companyName: 'Airbnb',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg',
    position: 'Full Stack Engineer',
    expires: '2025-09-25',
    startingSalary: 65000,
    workType: WorkType.HYBRID,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'Experience with full-stack development and microservices',
    description:
      'Work on travel and hospitality solutions connecting millions of hosts and guests.',
    isApplied: false,
    companyAddress: '888 Brannan St, San Francisco, CA 94103',
    companyIndustry: 'Hospitality & Travel',
    companyWebsite: 'https://www.airbnb.com',
  },
  {
    id: 6,
    companyName: 'Netflix',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg',
    position: 'Backend Engineer',
    expires: '2025-09-30',
    startingSalary: 72000,
    workType: WorkType.REMOTE,
    location: 'Los Gatos, CA',
    country: 'USA',
    qualifications:
      'Experience in scalable backend systems and video streaming tech',
    description:
      'Develop backend systems powering Netflix’s global video streaming platform.',
    isApplied: false,
    companyAddress: '100 Winchester Cir, Los Gatos, CA 95032',
    companyIndustry: 'Entertainment / Streaming',
    companyWebsite: 'https://www.netflix.com',
  },
  {
    id: 7,
    companyName: 'Tesla',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg',
    position: 'Embedded Software Engineer',
    expires: '2025-09-18',
    startingSalary: 78000,
    workType: WorkType.ON_SITE,
    location: 'Austin, TX',
    country: 'USA',
    qualifications: 'Experience in embedded systems and automotive software',
    description:
      'Contribute to autonomous driving and electric vehicle innovations.',
    isApplied: false,
    companyAddress: '13101 Tesla Rd, Austin, TX 78725',
    companyIndustry: 'Automotive / Clean Energy',
    companyWebsite: 'https://www.tesla.com',
  },
  {
    id: 8,
    companyName: 'Meta',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/1200px-Meta_Platforms_Inc._logo.svg.png?20230620122121',
    position: 'Distributed Systems Engineer',
    expires: '2025-09-22',
    startingSalary: 76000,
    workType: WorkType.HYBRID,
    location: 'Menlo Park, CA',
    country: 'USA',
    qualifications:
      'Experience with large-scale distributed systems and social platforms',
    description:
      'Work on the metaverse, AI, and large-scale social networking technologies.',
    isApplied: false,
    companyAddress: '1 Hacker Way, Menlo Park, CA 94025',
    companyIndustry: 'Technology / Social Media',
    companyWebsite: 'https://about.meta.com',
  },
  {
    id: 9,
    companyName: 'Adobe',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Adobe_Corporate_logo.svg/768px-Adobe_Corporate_logo.svg.png?20220820114255',
    position: 'UI/UX Engineer',
    expires: '2025-09-28',
    startingSalary: 69000,
    workType: WorkType.REMOTE,
    location: 'San Jose, CA',
    country: 'USA',
    qualifications: 'Strong knowledge of UI/UX design and frontend development',
    description:
      'Build tools for creatives around the world in Photoshop, Illustrator, and XD.',
    isApplied: false,
    companyAddress: '345 Park Ave, San Jose, CA 95110',
    companyIndustry: 'Software / Design',
    companyWebsite: 'https://www.adobe.com',
  },
  {
    id: 10,
    companyName: 'IBM',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
    position: 'AI Engineer',
    expires: '2025-10-05',
    startingSalary: 71000,
    workType: WorkType.HYBRID,
    location: 'Armonk, NY',
    country: 'USA',
    qualifications: 'Knowledge in AI, machine learning, and enterprise systems',
    description: 'Develop AI-driven enterprise solutions for global clients.',
    isApplied: false,
    companyAddress: '1 Orchard Rd, Armonk, NY 10504',
    companyIndustry: 'Technology / Consulting',
    companyWebsite: 'https://www.ibm.com',
  },
  {
    id: 11,
    companyName: 'Twitter (X)',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/X_logo_2023_original.svg/450px-X_logo_2023_original.svg.png?20230728155658',
    position: 'API Engineer',
    expires: '2025-09-14',
    startingSalary: 68000,
    workType: WorkType.REMOTE,
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: 'Experience with real-time systems and large-scale APIs',
    description:
      'Help build the future of real-time communication and microblogging.',
    isApplied: false,
    companyAddress: '1355 Market St #900, San Francisco, CA 94103',
    companyIndustry: 'Technology / Social Media',
    companyWebsite: 'https://x.com',
  },
  {
    id: 12,
    companyName: 'Apple',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    position: 'iOS Developer',
    expires: '2025-09-29',
    startingSalary: 80000,
    workType: WorkType.ON_SITE,
    location: 'Cupertino, CA',
    country: 'USA',
    qualifications: 'Strong background in iOS/macOS development',
    description:
      'Work on cutting-edge hardware-software integrations across Apple products.',
    isApplied: false,
    companyAddress: '1 Apple Park Way, Cupertino, CA 95014',
    companyIndustry: 'Technology / Consumer Electronics',
    companyWebsite: 'https://www.apple.com',
  },
  {
    id: 13,
    companyName: 'Intel',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Intel_logo_%282020%2C_light_blue%29.svg/593px-Intel_logo_%282020%2C_light_blue%29.svg.png?20211214194140',
    position: 'Hardware Engineer',
    expires: '2025-09-27',
    startingSalary: 72000,
    workType: WorkType.HYBRID,
    location: 'Santa Clara, CA',
    country: 'USA',
    qualifications: 'Experience with chip design and semiconductor development',
    description: 'Contribute to next-gen processors and hardware innovations.',
    isApplied: false,
    companyAddress: '2200 Mission College Blvd, Santa Clara, CA 95054',
    companyIndustry: 'Semiconductors',
    companyWebsite: 'https://www.intel.com',
  },
  {
    id: 14,
    companyName: 'Shopify',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Shopify_logo_2018.svg/768px-Shopify_logo_2018.svg.png?20240107131458',
    position: 'E-commerce Developer',
    expires: '2025-10-02',
    startingSalary: 67000,
    workType: WorkType.REMOTE,
    location: 'Ottawa, Ontario',
    country: 'Canada',
    qualifications:
      'Experience with e-commerce platforms and full-stack development',
    description:
      'Help entrepreneurs build and scale online businesses globally.',
    isApplied: false,
    companyAddress: '151 O’Connor St, Ottawa, ON, Canada',
    companyIndustry: 'E-commerce / Software',
    companyWebsite: 'https://www.shopify.com',
  },
  {
    id: 15,
    companyName: 'Siemens',
    companyLogo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Siemens-logo.svg/1116px-Siemens-logo.svg.png?20130706103619',
    position: 'IoT Engineer',
    expires: '2025-09-26',
    startingSalary: 66000,
    workType: WorkType.ON_SITE,
    location: 'Munich',
    country: 'Germany',
    qualifications: 'Engineering background with IoT and automation experience',
    description:
      'Work on industrial automation and smart infrastructure solutions.',
    isApplied: false,
    companyAddress: 'Werner-von-Siemens-Straße 1, 80333 München, Germany',
    companyIndustry: 'Engineering / Electronics',
    companyWebsite: 'https://www.siemens.com',
  },
];
